"""add created at field in inbox

Revision ID: 9454d0569cc2
Revises: 5bd6ad9cf38f
Create Date: 2026-06-13 22:32:50.766324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9454d0569cc2'
down_revision: Union[str, Sequence[str], None] = '5bd6ad9cf38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'created_at')
    # ### end Alembic commands ###
